<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageVersion Include="CliWrap" Version="3.6.6" />
    <PackageVersion Include="Keyfactor.Orchestrators.IOrchestratorJobExtensions" Version="1.0.0" />
    <PackageVersion Include="Keyfactor.PKI" Version="8.1.1" />
    <PackageVersion Include="Keyfactor.Platform.ICertificateStoreTypeMigrationHandler" Version="0.0.0-PRERELEASE-96152-ae5ad82032" />
    <PackageVersion Include="Microsoft.PowerShell.SDK" Version="7.4.13" />
    <PackageVersion Include="SSH.NET" Version="2025.1.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageVersion Include="xunit" Version="2.4.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.3" />
    <PackageVersion Include="coverlet.collector" Version="3.1.2" />
  </ItemGroup>
</Project>